### ISSUE TITLE
Remove extraArgs?

### ISSUE THREAD

**Issue by benley** [singlestore-labs/tailscale-manager#4]
Is there actually a use case for `extraArgs`?  Anything you could do with that could also be done with a single invocation of `tailscale set`, so what is the point of having it in tailscale-manager?

**Comment by benley** [comment]
I'm not sure what happened to it but someone commented with this a few weeks ago:

> It's useful in some cases. For example, we run Tailscale in a container, and the tailscaled socket is stored in /tmp/tailscaled.sock, so we need to append `--socket="/tmp/tailscaled.sock` to tailscale set commands for them to work properly

**Comment by SamyDjemai** [comment]
Yep that was me! I removed my comment because the socket arg has to be defined outside of the `extraArgs`, see #10

**Comment by benley** [comment]
Oh, I see that now!  I'm just starting to catch up after a few weeks away.  What do you think, is `extraArgs` something we should keep around as an escape hatch?

**Comment by SamyDjemai** [comment]
I don't see any use for it right now, but I don't feel like it's enough to delete it 😅 I'd keep it around IMO
